title: Electrobytes' Lab
description: Test and play around anything that has 1's and 0's

domain: electrbytes.github.io
url: https://electrobytes.github.io
baseurl: /

theme: jekyll-theme-hacker
plugins:
  - jekyll-remote-theme